### DISCUSSION TITLE
Same air.toml file for both Windows and Linux?

### DISCUSSION THREAD

**Discussion by frederikhors** [air-verse/air#231] [Q&A]
If I use the same air.toml file for both Windows and MacOS I need a way to handle the build command file?

Right now on Windows:

```toml
[build]
bin = "tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ."
```

How to handle the same for a Mac / Linux OS?
