### DISCUSSION TITLE
Exit air when process exits

### DISCUSSION THREAD

**Discussion by bliepp** [air-verse/air#581] [Q&A]
Hey there, I'm currently writing an app where I want to be able to shut it down from within the UI, i.e. my program exits at some point using `os.Exit(0)`. I use air for development and while the program actually exits, air keeps running idle. So what I actually want is air to exit when the program exits. Is that even possible with air?

My current config:
```toml
[build]
  include_ext = ["go", "tpl", "tmpl", "html", "css", "scss", "js"]
  send_interrupt = true
  stop_on_error = false
```

When the program exits air logs `Process Exit with Code 0` and does not restart it. However, air is still running. I need to kill it manually using Ctrl+C.

KIndly
bliepp
