### DISCUSSION TITLE
How to use Air with `go run .` and skip the build step in Air.

### DISCUSSION THREAD

**Discussion by ADTC** [air-verse/air#597] [Show and tell]
If you use `go run .`, Go will build and run in a single step. The build is stored in a random temporary folder in `/var`. Theoretically it's the same as using `go build -o ./tmp/main .` then running `./tmp/main`.

But if you're interested in using `go run .` by itself, here's how to do it:

```toml
bin = ""
cmd = "echo 'Skipping build step in Air...'"
full_bin = "go run ."
```

The trick is to use `full_bin` instead of `bin` because the former is a proper shell command, while the latter is just a file reference.

Note: Unfortunately this still creates an empty `tmp` directory.
