### DISCUSSION TITLE
How to edit .air.toml of [build].bin and cmd support windows and linux?

### DISCUSSION THREAD

**Discussion by seepine** [air-verse/air#772] [Q&A] [answered]
In macos, run `air init` and generate config file, and git commit to github

```toml
root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp"

[build]
  args_bin = []
  bin = "./.tmp/main"
  cmd = "go build -o ./.tmp/main ."
```

But in windows, git clone and run cmd `air`, it cannot not work
