### ISSUE TITLE
only watch file in root folder

### ISSUE THREAD

**Issue by iqbaldp78** [air-verse/air#197]
i have project directory like this :

```
cmd
----app
--------main.go
commands.go
.env
```

my ```.air.toml```
```
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "." 
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o tmp/server ./cmd/app/."

# Binary file yields from `cmd`.
bin = "tmp"

# Customize binary.
# This is how you start to run your application. Since my application will works like CLI, so to run it, like to make a CLI call.
full_bin = "APP_ENV=dev APP_USER=air ./tmp/server"

# This log file places in your tmp_dir.
log = "air_errors.log"

# Watch these filename extensions.
include_ext = ["go","tpl", "tmpl", "html", "yml", "toml","env"]

# Ignore these filename extensions or directories.
exclude_dir = []

# Watch these directories if you specified.
include_dir = []

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

# Exclude specific regular expressions.
# exclude_regex = ["_test.go"]

# Stop running old binary when build errors occur.
stop_on_error = true

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false

# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true
```

when try to save .env file its reload as well, but when i try to save main.go file under dir cmd/app/main.go . does not work ..

can someone help me ??

**Comment by cozzbie** [comment]
Interesting. The reverse here is the case for me. Air does not track root changes but does quite fine once files are in a sub directory.

**Comment by rochinworks** [comment]
I have a similar problem and tried `"*", "."` but neither worked for root files.

**Comment by Falldot** [comment]
Hi, I have a similar problem

My project directory:
![image](https://user-images.githubusercontent.com/86632059/174779230-fa45dbdc-901a-45cc-ba51-242dc6b55dde.png)

my .air.toml:
```toml
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
  # cmd = "make build-api"
  cmd = "go build -o ./tmp/main ./cmd/user_service/main.go"
  bin = "tmp/main"
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env", "yaml"]
  exclude_dir = ["tmp", "assets", "vendor", "bin", "build", "deploy"]
  include_dir = []
  exclude_regex = ["_test.go"]
  exclude_file = []
  exclude_unchanged = true
  log = "air.log"
  args_bin = []
  stop_on_error = true
  send_interrupt = false
  delay = 1000
  kill_delay = 500

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false
```

When I save any file in the root, air rebuilds successfully, but ignores all subdirectories and files in them. Writing directories in the `include_dir` field does not solve this problem.
Use WSL2 Ubuntu 22.04.
