### ISSUE TITLE
Can't get excluding files and dirs via regex working

### ISSUE THREAD

**Issue by CanRau** [air-verse/air#249]
I've got files & folders with `.ignored.` in the name or ending in `.ignored`

I tried all of the following to exclude them

```toml
exclude_dir = ["tmp", ".ignored"]
exclude_regex = [".+\.ignored\.?.*", ".+\.ignored", ".+\.ignored\.+", "ignored"]
exclude_file = [".ignored", ".ignored."]
```

Tried the first regex via [Go Playground](https://go.dev/play/p/59ben6h4k-F)

Still showing `watching data.ignored/db` etc. only working seems `!exclude tmp`

I actually expected it to just work using

```toml
exclude_regex = [".+\.ignored\.?.*"]
```

<details>
<summary>complete .air.toml</summary>

```toml
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "." 
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/app/app cmd/serve/main.go"
# Binary file yields from `cmd`.
bin = "tmp/app"

# Customize binary.
# This is how you start to run your application. Since my application will works like CLI, so to run it, like to make a CLI call.
full_bin = "./tmp/app/app"
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", ".ignored"]
# exclude_regex = [".+\.ignored\.?.*", ".+\.ignored", ".+\.ignored\.+", "ignored"]
# exclude_file = [".ignored", ".ignored."]
# Exclude unchanged files.
exclude_unchanged = true
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
```
</details>
