### ISSUE TITLE
`include_file` should overrule `include_ext`

### ISSUE THREAD

**Issue by silverwind** [air-verse/air#350]
On `master` branch:

```toml
include_ext = ["go"]
include_file = ["main.go", "openapi.yaml"]
```

This config will not trigger a reload when `openapi.yaml` changes because its extension is missing in `include_ext`. I would say that the check via `include_ext` should be skipped in case of explicit inclusion via `include_file`.
