### ISSUE TITLE
not watching root when an exclude_dir is setup

### ISSUE THREAD

**Issue by larry868** [air-verse/air#372]
hi everyone,

**Issue:** not watching root when an *exclude_dir* is setup
**Air version:** 1.40.4 built with Go 1.18.3

## Reproduce

`.air.toml` file:

```toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/helloapp_server main.go"
bin = "./tmp/helloapp_server"
include_ext = ["go"]
```

Air is watching root `.`
![image](https://user-images.githubusercontent.com/13906379/211358313-5117761f-4119-4b06-9934-2116ea08fb3e.png)

Now add an exclude_dir setup 
`.air.toml` file:

```toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/helloapp_server main.go"
bin = "./tmp/helloapp_server"
include_ext = ["go"]

exclude_dir = ["build", "website", "web", "vendor", "testdata"]
```

Air is no more watching root:
![image](https://user-images.githubusercontent.com/13906379/211359127-9fa024e5-99e6-4345-9d5f-6e7c84b36c97.png)
