### ISSUE TITLE
Panic in proxy handler

### ISSUE THREAD

**Issue by jtackaberry** [air-verse/air#634]
Given the following configuration

```toml
root = "."

[build]
  bin = "myproject"
  cmd = "make"
  delay = 200
  exclude_dir = ["vendor"]
  include_ext = ["go", "html", "css"]
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500000000000 # nanosecond

[log]
  time = true

[misc]
  clean_on_exit = true

[proxy]
  enabled = true
  proxy_port = 8080
  app_port = 7070
```

I sometimes observe the following panic:

```
2024/08/21 10:50:12 http: panic serving 127.0.0.1:44908: runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
net/http.(*conn).serve.func1()
        /opt/go-1.22.4/src/net/http/server.go:1898 +0xbe
panic({0x860820?, 0xc9e4d0?})
        /opt/go-1.22.4/src/runtime/panic.go:770 +0x132
github.com/air-verse/air/runner.(*Proxy).proxyHandler(0xc0001dc210, {0x99b2e0, 0xc0000b00e0}, 0xc0003acc60)
        /home/jtackaberry/src/go/pkg/mod/github.com/air-verse/air@v1.52.3/runner/proxy.go:122 +0x599
net/http.HandlerFunc.ServeHTTP(0xcb58a0?, {0x99b2e0?, 0xc0000b00e0?}, 0x7bef5a?)
        /opt/go-1.22.4/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x46bfb9?, {0x99b2e0, 0xc0000b00e0}, 0xc0003acc60)
        /opt/go-1.22.4/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc0002ac0c0?}, {0x99b2e0?, 0xc0000b00e0?}, 0x6?)
        /opt/go-1.22.4/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0001c65a0, {0x99bb50, 0xc0000b42a0})
        /opt/go-1.22.4/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 32
        /opt/go-1.22.4/src/net/http/server.go:3285 +0x4b4
```
