### ISSUE TITLE
The Docker container fails to restart with cosmtrek/air

### ISSUE THREAD

**Issue by stephenwithav** [air-verse/air#657]
Nothing changes when I run `docker compose up --build` and save a file in [this repo](https://github.com/Bootstrapping-Microservices-in-Go/chapter-05/tree/air-issue/example-01).

My `docker-compose.yml` file:

```docker
version: "3"
services:
  video-streaming:
    image: cosmtrek/air
    working_dir: /project-package/
    container_name: video-streaming
    ports:
      - "4000:80"
    volumes:
      - ./video-streaming/:/project-package/
    environment:
      - PORT=80

  history:
    image: cosmtrek/air
    working_dir: /project-package/
    container_name: history
    ports:
      - "4001:80"
    volumes:
      - ./history/:/project-package/
    environment:
      - PORT=80
    restart: "no"
```

Am I overlooking something stupid?  (Likely so.)

```
OS: Linux work 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

The `history` and `video-streaming` services work great when I `cd` into them and run `air`, but not via `docker compose`.

**Comment by stephenwithav** [comment]
Changing the `Dockerfile` to install `air` and mounting the directory in the container made it work:

```dockerfile
FROM golang:1.23
RUN go install github.com/air-verse/air@latest
ADD . /src
WORKDIR /src
ENV CGO_ENABLED=0
CMD ["air"]
```

```yaml
version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4000:80"
    volumes:
      - ./video-streaming:/src
    environment:
      - PORT=80
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: "no"
```
