### ISSUE TITLE
Live reload not working - reload script not injected

### ISSUE THREAD

**Issue by pczern** [air-verse/air#667]
Live Reload refresh isn't working in the browser, the go app rebuilds on any changes but the browser isn't reloading.

With GoFiber I am creating a server like

```go
log.Fatal(app.Listen(":3000"))
```

Rendering the page on route /
```go
app.Get("/", func(c *fiber.Ctx) error {
		return c.Render("page/index", &fiber.Map{}, "layout/layout-default")
	})
```

but when I change anything in "page/index" I have to manually refresh. And the `layout-default` I am rendering the page with contains a `<body>` element.

```toml
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
cmd = "task build"
bin = "main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp"]
include_dir = ["src"]
exclude_file = []
exclude_unchanged = false
follow_symlink = false
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 0      # ms
poll = false
poll_interval = 500

[log]
time = true
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = true
proxy_port = 3001
app_port = 3000
```
