### ISSUE TITLE
Graceful shutdown not happening

### ISSUE THREAD

**Issue by amir20** [air-verse/air#720]
Hello, 

I moved to air from reflex. I have the following code : 

```go
ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
defer stop()
go func() {
  log.Info().Msgf("Dozzle agent version %s", args.Version())
  log.Info().Msgf("Agent listening on %s", listener.Addr().String())

  if err := server.Serve(listener); err != nil {
	log.Error().Err(err).Msg("failed to serve")
  }
}()
<-ctx.Done()
stop()
log.Info().Msg("Shutting down agent")
```

It seems that `Shutting down agent` is never executed. 

I have some clean up that need to do but it never gets triggered. I see _A LOT_ of issues about this. But I can't tell if I am doing something wrong. Here is my config: 

```toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/dozzle"
cmd = "go build -race -o ./tmp/dozzle ."
delay = 1000
exclude_dir = [
  "assets",
  "tmp",
  "data",
  "node_modules",
  "docs",
  "test-results",
  "dist",
  "e2e",
  "examples",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = ["rm -f agent-*.addr"]
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
```
