### ISSUE TITLE
Cannot reload if the .env file changed

### ISSUE THREAD

**Issue by ahmadhabibi14** [air-verse/air#733]
I want my app to reload if I change file `.env` or `.env.override`. Here's my config file `.air.toml`

```toml
root = "."

[build]
include_ext = ['go', 'html', '.override', '.env']
inclide_file = ['.env.override', '.env']
exclude_regex = ['_test.go']
exclude_dir = ['backup', '_tmpdb', 'tmp', 'deploy', 'static', 'svelte/node_modules', 'svelte/assets']
delay = 500
stop_on_error = true
```

I also tried running it with command `air -c .air.toml -- web` to clarify the use of `.air.toml` config file
